# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  encoding: unicode
  database: tgn_development
  host: localhost
  pool: 5
  username: alexhick
  password:
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: tgn_test
  host: localhost
  
  username: alexhick
  password:
  template: template0

production:
  adapter: postgresql
  encoding: unicode
  database: alexsplatform
  pool: 5
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>
  # socket: <%=ENV['OPENSHIFT_MYSQL_DB_SOCKET']%>
  host: <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>

