# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  encoding: unicode
  database: tgn_development
  host: localhost
  pool: 5
  username: alexhick
  password:
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: tgn_test
  host: localhost
  pool: 5
  username: alexhick
  password:
  template: template0

production:
  adapter: postgresql
  encoding: unicode
  database: alexsplatform
  host: postgresql://$OPENSHIFT_POSTGRESQL_DB_HOST:$OPENSHIFT_POSTGRESQL_DB_PORT/

  username: admin
  password: Nb-mzwuqWQX1
  template: template0

